/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_rafaelflores_31711187;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Faith
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Users.add(new Persona("Rafael", "Flores", "rafac", "1234", new Date(), 21, Color.cyan));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDiagLogin = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUserR = new javax.swing.JTextField();
        txtPassR = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnColor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPopAgregarCarta = new javax.swing.JPopupMenu();
        jMenu3 = new javax.swing.JMenu();
        jItemM1 = new javax.swing.JMenuItem();
        jItemM2 = new javax.swing.JMenuItem();
        jItemM3 = new javax.swing.JMenuItem();
        jDiagModificarCarta = new javax.swing.JDialog();
        lblTitulo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtDaño = new javax.swing.JTextField();
        txtPtsVida = new javax.swing.JTextField();
        btnMod = new javax.swing.JButton();
        jPopOpcionCarta = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeMazos = new javax.swing.JTree();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCartas = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setText("Login");

        label2.setText("Usuario");

        jLabel3.setText("Contraseña");

        btnIngresar.setText("Ingresar");
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(btnIngresar)
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUser)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(191, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(btnIngresar)
                .addGap(94, 94, 94))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label2)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(189, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Ingreso", jPanel2);

        jLabel4.setText("Usuario");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Fecha Nacimiento");

        jLabel7.setText("Nombre");

        jLabel8.setText("Apellido");

        jLabel9.setText("Color Fav.");

        btnRegistro.setText("Registrarse");
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
        });

        btnColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassR, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtUserR, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(btnRegistro)
                            .addComponent(btnColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUserR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(btnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnRegistro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro", jPanel3);

        javax.swing.GroupLayout jDiagLoginLayout = new javax.swing.GroupLayout(jDiagLogin.getContentPane());
        jDiagLogin.getContentPane().setLayout(jDiagLoginLayout);
        jDiagLoginLayout.setHorizontalGroup(
            jDiagLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDiagLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jDiagLoginLayout.setVerticalGroup(
            jDiagLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDiagLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jLabel2.setText("jLabel2");

        jMenu3.setText("Agregar Carta...");

        jItemM1.setText("Mazo 1");
        jItemM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemM1ActionPerformed(evt);
            }
        });
        jMenu3.add(jItemM1);

        jItemM2.setText("Mazo 2");
        jItemM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemM2ActionPerformed(evt);
            }
        });
        jMenu3.add(jItemM2);

        jItemM3.setText("Mazo 3");
        jItemM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemM3ActionPerformed(evt);
            }
        });
        jMenu3.add(jItemM3);

        jPopAgregarCarta.add(jMenu3);

        lblTitulo.setText("Modificar");

        jLabel13.setText("Daño");

        jLabel14.setText("Puntos de Vida");

        btnMod.setText("Modificar");
        btnMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDiagModificarCartaLayout = new javax.swing.GroupLayout(jDiagModificarCarta.getContentPane());
        jDiagModificarCarta.getContentPane().setLayout(jDiagModificarCartaLayout);
        jDiagModificarCartaLayout.setHorizontalGroup(
            jDiagModificarCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDiagModificarCartaLayout.createSequentialGroup()
                .addGroup(jDiagModificarCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDiagModificarCartaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDiagModificarCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(jDiagModificarCartaLayout.createSequentialGroup()
                                .addGroup(jDiagModificarCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(46, 46, 46)
                                .addGroup(jDiagModificarCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDaño, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(txtPtsVida)))))
                    .addGroup(jDiagModificarCartaLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnMod)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jDiagModificarCartaLayout.setVerticalGroup(
            jDiagModificarCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDiagModificarCartaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDiagModificarCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtDaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDiagModificarCartaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPtsVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMod)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jMenuItem1.setText("jMenuItem1");
        jPopOpcionCarta.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jPopOpcionCarta.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setEnabled(false);

        jTabbedPane2.setEnabled(false);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mazos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo 1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo 2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo 3");
        treeNode1.add(treeNode2);
        jTreeMazos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTreeMazos);

        jLabel10.setText("Mazos");

        jListCartas.setModel(new DefaultListModel());
        jListCartas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCartasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListCartas);

        jLabel11.setText("Cartas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(378, 378, 378))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Inicio", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Clan", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab3", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jMenu1.setText("Log-in");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        if (this.txtUser.getText().equals("") && this.txtPass.getText().equals("")) {
           JOptionPane.showMessageDialog(this.jDiagLogin, "Debe llenar todos los campos!!!!"); 
        }
        if (this.Users.isEmpty()) {
            JOptionPane.showMessageDialog(this.jDiagLogin, "Su Uusario no existe, registrese en nuestro sistema!!!!");
        }else{
            for (int i = 0; i < Users.size(); i++) {
                if (Users.get(i).getUser().equals(this.txtUser.getText()) 
                        && Users.get(i).getPass().equals(this.txtPass.getText())) {
                    JOptionPane.showMessageDialog(this.jDiagLogin, "Bienvenido al Sistema!!!!");
                    this.jTabbedPane2.setEnabled(true);
                    this.log = true;
                    this.jDiagLogin.dispose();
                    UActual = Users.get(i);
                    CargarCartas();
                    return;
                }
            }
            JOptionPane.showMessageDialog(this.jDiagLogin, "Su Uusario no existe, registrese en nuestro sistema!!!!");
        }
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
        if (this.txtUserR.getText().equals("") || this.txtPassR.getText().equals("") || this.txtNombre.getText().equals("")
                || this.txtApellido.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos!!!!!!");
        }else{
            Date fechaN = this.jDateChooser1.getDate(), fecha = new Date();
            long Edad = (fecha.getTime() - fechaN.getTime())/ (1000 * 60 * 60 * 24 /365);
            
            Users.add(new Persona(this.txtNombre.getText(), this.txtApellido.getText(), this.txtUser.getText(), this.txtPass.getText(),
            fechaN, (int)Edad, this.btnColor.getBackground()));
        }
    }//GEN-LAST:event_btnRegistroMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorMouseClicked
        this.btnColor.setBackground(JColorChooser.showDialog(this.jDiagLogin, "Escoja un color", Color.yellow));
    }//GEN-LAST:event_btnColorMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.jDiagLogin.setModal(true); //Permite que al abrir la subventana, se bloquee la vista anterior
        this.jDiagLogin.pack();
        this.jDiagLogin.setLocationRelativeTo(this);
        this.jDiagLogin.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jListCartasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCartasMouseClicked
        if (jListCartas.getSelectedIndex()>=0){
            if(evt.isMetaDown()){
                this.jPopAgregarCarta.show(evt.getComponent(),evt.getX(),evt.getY());
            }
        }
    }//GEN-LAST:event_jListCartasMouseClicked

    private void jItemM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemM1ActionPerformed
        DefaultTreeModel modeloArbol = (DefaultTreeModel) this.jTreeMazos.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
        DefaultListModel modeloLista = (DefaultListModel) this.jListCartas.getModel();
        boolean exist = false;
        int centinela = -1;
        
        if (raiz.getChildAt(0).getChildCount() == 3) {
            JOptionPane.showMessageDialog(this, "Ya no puede añadir más cartas");
        }else{
            this.lblTitulo.setText("Ingrese lo sisguiente Valores para crear la carta:");
            this.jDiagModificarCarta.setModal(true); //Permite que al abrir la subventana, se bloquee la vista anterior
            this.jDiagModificarCarta.pack();
            this.jDiagModificarCarta.setLocationRelativeTo(this);
            this.jDiagModificarCarta.setVisible(true);
            actual = ((Cartas) modeloLista.get(this.jListCartas.getSelectedIndex()));
            for (int i = 0; i < raiz.getChildAt(0).getChildCount(); i++) {
                if (raiz.getChildAt(0).getChildAt(i).toString().equals(actual.getNombre())) {
                    JOptionPane.showMessageDialog(this, "Este Nodo ya existe!!!");
                    exist = true;
                }
            }
            if (!exist) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(actual);
                ((DefaultMutableTreeNode) raiz.getChildAt(0)).add(p);
            }
            UActual.setMazos(modeloArbol);
            modeloArbol.reload();
        }
    }//GEN-LAST:event_jItemM1ActionPerformed

    private void jItemM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemM2ActionPerformed
        DefaultTreeModel modeloArbol = (DefaultTreeModel) this.jTreeMazos.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
        DefaultListModel modeloLista = (DefaultListModel) this.jListCartas.getModel();
        boolean exist = false;
        
        if (raiz.getChildAt(1).getChildCount() == 3) {
            JOptionPane.showMessageDialog(this, "Ya no puede añadir más cartas");
        }else{
            this.lblTitulo.setText("Ingrese lo sisguiente Valores para crear la carta:");
            
            this.jDiagModificarCarta.setModal(true); //Permite que al abrir la subventana, se bloquee la vista anterior
            this.jDiagModificarCarta.pack();
            this.jDiagModificarCarta.setLocationRelativeTo(this);
            this.jDiagModificarCarta.setVisible(true);
            actual = ((Cartas) modeloLista.get(this.jListCartas.getSelectedIndex()));
            for (int i = 0; i < raiz.getChildAt(1).getChildCount(); i++) {
                if (raiz.getChildAt(1).getChildAt(i).toString().equals(actual.getNombre())) {
                    JOptionPane.showMessageDialog(this, "Este Nodo ya existe!!!");
                    exist = true;
                }
            }
            if (!exist) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(actual);
                ((DefaultMutableTreeNode) raiz.getChildAt(1)).add(p);
            }
            UActual.setMazos(modeloArbol);
            modeloArbol.reload();
        }
    }//GEN-LAST:event_jItemM2ActionPerformed

    private void jItemM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemM3ActionPerformed
        DefaultTreeModel modeloArbol = (DefaultTreeModel) this.jTreeMazos.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
        DefaultListModel modeloLista = (DefaultListModel) this.jListCartas.getModel();
        boolean exist = false;
        
        if (raiz.getChildAt(2).getChildCount() == 3) {
            JOptionPane.showMessageDialog(this, "Ya no puede añadir más cartas");
        }else{
            this.lblTitulo.setText("Ingrese lo sisguiente Valores para crear la carta:");
            this.jDiagModificarCarta.setModal(true); //Permite que al abrir la subventana, se bloquee la vista anterior
            this.jDiagModificarCarta.pack();
            this.jDiagModificarCarta.setLocationRelativeTo(this);
            this.jDiagModificarCarta.setVisible(true);
            actual = ((Cartas) modeloLista.get(this.jListCartas.getSelectedIndex()));
            for (int i = 0; i < raiz.getChildAt(2).getChildCount(); i++) {
                if (raiz.getChildAt(2).getChildAt(i).toString().equals(actual.getNombre())) {
                    JOptionPane.showMessageDialog(this, "Este Nodo ya existe!!!");
                    exist = true;
                }
            }
            if (!exist) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(actual);
                ((DefaultMutableTreeNode) raiz.getChildAt(2)).add(p);
            }
            UActual.setMazos(modeloArbol);
            modeloArbol.reload();
        }
    }//GEN-LAST:event_jItemM3ActionPerformed

    private void btnModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModMouseClicked
        try {
            if (this.txtDaño.getText().equals("") && this.txtPtsVida.getText().equals("")) {
                JOptionPane.showMessageDialog(this.jDiagModificarCarta, "Debe llenar ambos campos");
            }else{
                actual.setDaño(Integer.valueOf(this.txtDaño.getText()));
                actual.setPtsVida(Integer.valueOf(this.txtPtsVida.getText()));
                this.txtDaño.setText("");
                this.txtPtsVida.setText("");
                this.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this.jDiagModificarCarta, "No puede Ingresar datos que no sean numéricos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModMouseClicked

    public void CargarCartas(){
        DefaultListModel list = (DefaultListModel)this.jListCartas.getModel();
        for (int i = 0; i < 2; i++) {
            list.addElement(l.getPosiblesCarta().get(i));
            list.addElement(e.getPosiblesCarta().get(i));
            list.addElement(es.getPosiblesCarta().get(i));
            list.addElement(c.getPosiblesCarta().get(i));
        }
        
        this.jListCartas.setModel(list);
        if (UActual.getMazos() != null) {
            this.jTreeMazos.setModel(UActual.getMazos());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnRegistro;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JDialog jDiagLogin;
    private javax.swing.JDialog jDiagModificarCarta;
    private javax.swing.JMenuItem jItemM1;
    private javax.swing.JMenuItem jItemM2;
    private javax.swing.JMenuItem jItemM3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListCartas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopAgregarCarta;
    private javax.swing.JPopupMenu jPopOpcionCarta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTree jTreeMazos;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDaño;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPassR;
    private javax.swing.JTextField txtPtsVida;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUserR;
    // End of variables declaration//GEN-END:variables
    ArrayList<Persona> Users = new ArrayList();
    Legendaria l = new Legendaria();
    Epica e = new Epica();
    Especial es = new Especial();
    Comun c = new Comun();
    Cartas actual;
    Persona UActual;
    
    boolean log = false;
    

}
